[project]
name = "cosine-similarity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.97.0",
    "sentence-transformers>=5.0.0",
]
